### ISSUE TITLE
005_gitlab_ci  v0.11.0-alpha.3 version fails to import schema

### ISSUE THREAD

**Issue by unixsurfer** [cue-labs/cue-by-example#40]
With:
```bash
❯ cue version
cue version v0.11.0-alpha.3

go version go1.23.2
      -buildmode exe
       -compiler gc
       -trimpath true
     CGO_ENABLED 0
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
cue.lang.version v0.11.0
```
importing the schema fails:
```bash
➜ curl -o internal/ci/gitlab/gitlab.cicd.pipeline.schema.json https://gitlab.com/gitlab-org/gitlab/-/raw/7aa6170c4c81a98f372d7c52f3918858c4b69cca/app/assets/javascripts/editor/schema/ci.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 86518  100 86518    0     0   297k      0 --:--:-- --:--:-- --:--:--  298k

➜ cue import internal/ci/gitlab/gitlab.cicd.pipeline.schema.json -p gitlab -l '#Pipeline:'
unsupported Perl regexp syntax in "^(https?://|/?.?-?(?!\\w+://)\\w).+\\.ya?ml$": error parsing regexp: invalid or unsupported Perl syntax: `(?!`:
    ./internal/ci/gitlab/gitlab.cicd.pipeline.schema.json:390:11
unsupported Perl regexp syntax in "^(?!.*\\/)^(.*[^.]+.*)$": error parsing regexp: invalid or unsupported Perl syntax: `(?!`:
    ./internal/ci/gitlab/gitlab.cicd.pipeline.schema.json:1402:15
```
cue v0.10.0 version works fine

**Comment by jpluscplusm** [comment]
I think we can document on a v0.11-related minimum for this guide. That was the fix I put in for the GitHub equivalent, in https://github.com/cue-labs/cue-by-example/commit/bb252a9678ac99c46613a228b1581e1c7631a9b7, because figuring out an invocation that worked with both 0.10, <0.10, and >0.10 was really really fiddly. 

I do think @mvdan's point about the DX on upgrading is worth thinking about. My solution in the GitHub guide was basically driven by the upgrade being too involved to figure out in any kind of a backwards (or do I mean forwards?) compatible way.

**Comment by unixsurfer** [comment]
> The reason for this is that the new version actually understands about the `format` keyword rather than ignoring it. You can still run `cue import` in "best-effort" mode so that it will not generate constraints for features that it doesn't implement by using the new `strictFeatures` filetype mode:
> 
> ```
> cue import jsonschema+strictFeatures=0: internal/ci/gitlab/gitlab.cicd.pipeline.schema.json -p gitlab -l '#Pipeline:'
> ```

That did the trick. Thanks a lot.

**Comment by jpluscplusm** [comment]
I'll update this guide after `v0.11.0-alpha.4` is released, which is anticipated to have some differences wrt. default JSONSchema handling. The WIP changes are proposed in #38, which will be updated once alpha.4 is available.

**Comment by jpluscplusm** [comment]
The guide has been updated to reflect a minimum version requirement of `v0.11.0-alpha.4`, and the commands that it demonstrates are being testing in CI so they have less chance to bitrot in the future. Thanks for reporting this, @unixsurfer!
